#!/usr/bin/env bash
# File       : gen_version
# Created    : Wed Jan 15 2020 09:18:54 PM (+0100)
# Author     : Fabian Wermelinger
# Description: Generate CubismNova build version strings
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

BRANCH=""
VERSION=""
VHEAD=""
if [[ ! -d '.git' ]]; then
    # this is a release
    found=$(find ../ -maxdepth 1 -type d -name "CubismNova-*" | wc -l)
    if [[ ${found:-0} -gt 0 ]]; then
        release=$(find ../ -maxdepth 1 -type d -name "CubismNova-*" | sort | tail -n1)
        release="$(basename ${release})"
        release="${release#CubismNova-}"
        if [[ ${found} -gt 1 ]]; then
            echo "WARNING: More than one CubismNova releases found.  Will use latest ${release}"
        fi
        BRANCH="master"
        VERSION="${release}"
        VHEAD="${release}"
    else
        BRANCH="UNKNOWN-BRANCH"
        VERSION="UNKNOWN-RELEASE"
        VHEAD="UNKNOWN-HEAD"
    fi
else
    # this is a git repository
    BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    VERSION="$(git describe --abbrev=0)"
    VHEAD="$(git describe --long --dirty --broken)"
fi


cat <<EOF > ${1}/Version.cpp
// File       : Version.cpp
// Created    : Wed Jan 15 2020 08:54:33 PM (+0100)
// Author     : Fabian Wermelinger
// Description: CubismNova build version strings
// Copyright 2020 ETH Zurich. All Rights Reserved.

#include "Cubism/Common.h"

NAMESPACE_BEGIN(Cubism)
NAMESPACE_BEGIN(Util)

const char *CubismVersion = "${VERSION}";
const char *CubismVersionHEAD = "${VHEAD}";
const char *CubismBranch = "${BRANCH}";

NAMESPACE_END(Util)
NAMESPACE_END(Cubism)
EOF
echo -n "${VERSION#*v}"
exit 0
