#!/usr/bin/env bash
# File       : gen_version
# Created    : Wed Jan 15 2020 09:18:54 PM (+0100)
# Author     : Fabian Wermelinger
# Description: Generate CubismNova build version strings
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
VERSION="$(git describe --abbrev=0)"
VHEAD="$(git describe --long --dirty --broken)"

cat <<EOF > ${1}/Version.cpp
// File       : Version.cpp
// Created    : Wed Jan 15 2020 08:54:33 PM (+0100)
// Author     : Fabian Wermelinger
// Description: CubismNova build version strings
// Copyright 2020 ETH Zurich. All Rights Reserved.

#include "Common.h"

NAMESPACE_BEGIN(Cubism)
NAMESPACE_BEGIN(Util)

const char *CubismVersion = "${VERSION}";
const char *CubismVersionHEAD = "${VHEAD}";
const char *CubismBranch = "${BRANCH}";

NAMESPACE_END(Util)
NAMESPACE_END(Cubism)
EOF
exit 0
