#!/usr/bin/env bash
# File       : tag_version.sh
# Created    : Wed Jan 15 2020 11:02:33 AM (+0100)
# Author     : Fabian Wermelinger
# Description: Utility to tag versions
#              This tool must be run from the project root.
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

# version argument must be passed following the specifications at
# https://semver.org/
VERSION="$(cat VERSION)"
git tag -e -a "v${VERSION}" -m "Release version ${VERSION}"
exit $?
