version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - run:
          name: Install dependencies
          command: apt-get update && apt-get -y install mpich cmake git

      - checkout

      - run:
          name: Debug Build and Test
          command: ./cmake_init.sh && cd debug && make -j && make test
