version: 2

aliases:
    - &buster_image
        docker:
            - image: debian:buster

jobs:
    debian_deps:
        steps:
            - run:
                name: Install Debian dependencies
                command: >
                    apt-get update && apt-get -y install
                    mpich
                    cmake
                    git
                    curl
                    libhdf5-mpich-dev

    code_checkout:
        steps:
            - checkout
            - run:
                name: Initalize submodules
                command: git submodule update --init

    debug_and_coverage:
        steps:
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_COVERAGE=ON &&
                    cd debug &&
                    make -j && make gcov && make install

    release:
        steps:
            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./install &&
                    cd release &&
                    make -j && make test && make install

    debug_32bit_index:
        steps:
            - run:
                name: Debug build (full; 32bit index)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_32BIT_INDEX=ON &&
                    cd debug &&
                    make -j && make test && make install

    debug_no_IO:
        steps:
            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test && make install

workflows:
    version: 2
    debian_buster:
        <<: *buster_image
        jobs:
            - debian_deps
            - code_checkout
            - debug_and_coverage:
                requires:
                    - debian_deps
                    - code_checkout
            - release:
                requires:
                    - debian_deps
                    - code_checkout
            - debug_32bit_index:
                requires:
                    - debian_deps
                    - code_checkout
            - debug_no_IO:
                requires:
                    - debian_deps
                    - code_checkout
