version: 2

jobs:
    build:
        docker:
            - image: debian:buster

        steps:
            - run:
                name: Install dependencies
                command: >
                    apt-get update && apt-get -y install
                    mpich
                    cmake
                    git
                    curl
                    libhdf5-mpich-dev

            - checkout

            - run:
                name: Initalize submodules
                command: git submodule update --init

            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_COVERAGE=ON &&
                    cd debug &&
                    make -j && make gcov && make install

            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./install &&
                    cd release &&
                    make -j && make test && make install

            - run:
                name: Debug build (full; 32bit index)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_32BIT_INDEX=ON &&
                    cd debug &&
                    make -j && make test && make install

            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test && make install
