version: 2.1

executors:
    buster_mpich:
        docker:
            - image:  docker.io/cselab/debian_buster_mpich:latest

    buster_openmpi:
        docker:
            - image:  docker.io/cselab/debian_buster_openmpi:latest

    fedora_mpich:
        docker:
            - image:  docker.io/cselab/fedora_mpich:latest

    fedora_openmpi:
        docker:
            - image:  docker.io/cselab/fedora_openmpi:latest

    focal_mpich:
        docker:
            - image:  docker.io/cselab/ubuntu_focal_mpich:latest

    focal_openmpi:
        docker:
            - image:  docker.io/cselab/ubuntu_focal_openmpi:latest

commands:
    checkout_code:
        steps:
            - checkout
            - run:
                name: Initalize submodules
                command: git submodule update --init --recursive

jobs:
    debug_and_coverage:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                  meson setup build --buildtype=debug -Db_coverage=true &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install &&
                  ninja -C build -j 1 coverage &&
                  ./tools/quality/codecov
            - store_artifacts:
                path: build/meson-logs/coveragereport

    debug:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                  meson setup build --buildtype=debug --prefix=~/test_install &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install

    release:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Release build (full)
                command: >
                  meson setup build --buildtype=release --prefix=~/test_install &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install

    debug_32bit_index:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full; 32bit index)
                command: >
                  meson setup build --buildtype=debug --prefix=~/test_install -DCUBISM_32BIT_INDEX=true &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install

    debug_no_IO:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (no libCubismIO)
                command: >
                  meson setup build --buildtype=debug --prefix=~/test_install -DCUBISM_IO=false &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install

workflows:
    debian:
        jobs:
            # - debug_and_coverage:
            #     image: buster_mpich
            # - release:
            #     image: buster_mpich
            # - debug_32bit_index:
            #     image: buster_mpich
            # - debug_no_IO:
            #     image: buster_mpich
            - debug_and_coverage:
                image: buster_openmpi
            - release:
                image: buster_openmpi
            - debug_32bit_index:
                image: buster_openmpi
            - debug_no_IO:
                image: buster_openmpi

    # fedora:
    #     jobs:
    #         # - debug_and_coverage:
    #         #     image: fedora_mpich
    #         # - release:
    #         #     image: fedora_mpich
    #         # - debug_32bit_index:
    #         #     image: fedora_mpich
    #         # - debug_no_IO:
    #         #     image: fedora_mpich
    #         - debug_and_coverage:
    #             image: fedora_openmpi
    #         - release:
    #             image: fedora_openmpi
    #         - debug_32bit_index:
    #             image: fedora_openmpi
    #         - debug_no_IO:
    #             image: fedora_openmpi

    # ubuntu:
    #     jobs:
    #         # - debug_and_coverage:
    #         #     image: focal_mpich
    #         # - release:
    #         #     image: focal_mpich
    #         # - debug_32bit_index:
    #         #     image: focal_mpich
    #         # - debug_no_IO:
    #         #     image: focal_mpich
    #         - debug_and_coverage:
    #             image: focal_openmpi
    #         - release:
    #             image: focal_openmpi
    #         - debug_32bit_index:
    #             image: focal_openmpi
    #         - debug_no_IO:
    #             image: focal_openmpi
