version: 2.1

executors:
    buster_mpich:
        docker:
            - image:  cselab/debian_buster_mpich:latest

    buster_openmpi:
        docker:
            - image:  cselab/debian_buster_openmpi:latest

commands:
    checkout_code:
        steps:
            - checkout
            - run:
                name: Initalize submodules
                command: git submodule update --init

jobs:
    debug_and_coverage:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_COVERAGE=ON &&
                    cd debug &&
                    make -j && make gcov && make install

    debug:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install &&
                    cd debug &&
                    make -j && make test && make install

    release:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./install &&
                    cd release &&
                    make -j && make test && make install

    debug_32bit_index:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full; 32bit index)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_32BIT_INDEX=ON &&
                    cd debug &&
                    make -j && make test && make install

    debug_no_IO:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test && make install

workflows:
    debian:
        jobs:
            - debug_and_coverage:
                image: buster_mpich
            - release:
                image: buster_mpich
            - debug_32bit_index:
                image: buster_mpich
            - debug_no_IO:
                image: buster_mpich
            - debug:
                image: buster_openmpi
            - release:
                image: buster_openmpi
            - debug_32bit_index:
                image: buster_openmpi
            - debug_no_IO:
                image: buster_openmpi
