version: 2.1

executors:
    buster:
        docker:
            - image: debian:buster

jobs:
    debian_deps:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Install Debian dependencies
                command: >
                    apt-get update && apt-get -y install
                    mpich
                    cmake
                    git
                    curl
                    libhdf5-mpich-dev

    code_checkout:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - checkout
            - run:
                name: Initalize submodules
                command: git submodule update --init

    debug_and_coverage:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_COVERAGE=ON &&
                    cd debug &&
                    make -j && make gcov && make install

    debug:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install &&
                    cd debug &&
                    make -j && make test && make install

    release:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./install &&
                    cd release &&
                    make -j && make test && make install

    debug_32bit_index:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Debug build (full; 32bit index)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_32BIT_INDEX=ON &&
                    cd debug &&
                    make -j && make test && make install

    debug_no_IO:
        parameters:
            image:
                type: executor
        executor: << parameters.image >>
        steps:
            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test && make install

workflows:
    debian:
        jobs:
            - debian_deps:
                image: buster
            - code_checkout:
                image: buster
                requires:
                    - debian_deps
            - debug_and_coverage:
                image: buster
                requires:
                    - debian_deps
                    - code_checkout
            - release:
                image: buster
                requires:
                    - debian_deps
                    - code_checkout
            - debug_32bit_index:
                image: buster
                requires:
                    - debian_deps
                    - code_checkout
            - debug_no_IO:
                image: buster
                requires:
                    - debian_deps
                    - code_checkout
