version: 2.1

executors:
    buster_mpich:
        docker:
            - image:  docker.io/cselab/debian_buster_mpich:latest

    buster_openmpi:
        docker:
            - image:  docker.io/cselab/debian_buster_openmpi:latest

    fedora_mpich:
        docker:
            - image:  docker.io/cselab/fedora_mpich:latest

    fedora_openmpi:
        docker:
            - image:  docker.io/cselab/fedora_openmpi:latest

    ubuntu_mpich:
        docker:
            - image:  docker.io/cselab/ubuntu_mpich:rolling

    ubuntu_openmpi:
        docker:
            - image:  docker.io/cselab/ubuntu_openmpi:rolling

# TODO: [fabianw@mavt.ethz.ch; 2021-03-21] centos

commands:
    checkout_code:
        steps:
            - checkout
            - run:
                name: Initalize submodules
                command: git submodule update --init --recursive

jobs:
    coverage:
        parameters:
            image:
                type: executor
            CC:
                type: string
                default: gcc
            CXX:
                type: string
                default: g++
            buildtype:
                type: string
                default: debug
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                  CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install --buildtype=<< parameters.buildtype >> -Db_coverage=true &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install &&
                  ninja -C build -j 1 coverage &&
                  ./tools/quality/coverage &&
                  ./tools/quality/codecov -X search -X fix -f '*.gcov'
            - store_artifacts:
                path: build/meson-logs

    build:
        parameters:
            image:
                type: executor
            CC:
                type: string
                default: gcc
            CXX:
                type: string
                default: g++
            buildtype:
                type: string
                default: debug
            buildargs:
                type: string
                default: ""
        executor: << parameters.image >>
        steps:
            - checkout_code
            - run:
                name: Debug build (full, code coverage)
                command: >
                  CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install --buildtype=<< parameters.buildtype >> << parameters.buildargs >> &&
                  ninja -C build -j 1 test && 
                  ninja -C build -j 1 install
            - store_artifacts:
                path: build/meson-logs

workflows:
    coverage:
        jobs:
            - coverage:
                name: debian_buster_openmpi_debug
                image: buster_openmpi
            - coverage:
                name: debian_buster_openmpi_release
                image: buster_openmpi
                buildtype: release

    debian_openmpi_gcc:
        jobs:
            - build:
                name: debug
                image: buster_openmpi
            - build:
                name: release
                image: buster_openmpi
                buildtype: release
            - build:
                name: debug_32bit_index
                image: buster_openmpi
                buildargs: -DCUBISM_32BIT_INDEX=true
            - build:
                name: debug_without_IO
                image: buster_openmpi
                buildargs: -DCUBISM_IO=false


    # debian_openmpi_clang:
    #     jobs:
    #         - debug:
    #             image: buster_openmpi
    #             CC: clang
    #             CXX: clang++
    #         - release:
    #             image: buster_openmpi
    #             CC: clang
    #             CXX: clang++

    # debian_mpich_gcc:
    #     jobs:
    #         - debug_and_coverage:
    #             image: buster_mpich
    #         - debug:
    #             image: buster_mpich
    #         - debug_32bit_index:
    #             image: buster_mpich
    #         - debug_no_IO:
    #             image: buster_mpich
    #         - release:
    #             image: buster_mpich

    # fedora_openmpi_gcc:
    #     jobs:
    #         - debug_and_coverage:
    #             image: fedora_openmpi
    #         - debug:
    #             image: fedora_openmpi
    #         - debug_32bit_index:
    #             image: fedora_openmpi
    #         - debug_no_IO:
    #             image: fedora_openmpi
    #         - release:
    #             image: fedora_openmpi

    # fedora_openmpi_clang:
    #     jobs:
    #         - debug:
    #             image: fedora_openmpi
    #             CC: clang
    #             CXX: clang++
    #         - release:
    #             image: fedora_openmpi
    #             CC: clang
    #             CXX: clang++

    # fedora_gcc:
    #     jobs:
    #         # - debug_and_coverage:
    #         #     image: fedora_mpich
    #         # - release:
    #         #     image: fedora_mpich
    #         # - debug_32bit_index:
    #         #     image: fedora_mpich
    #         # - debug_no_IO:
    #         #     image: fedora_mpich
    #         - debug_and_coverage:
    #             image: fedora_openmpi
    #         - release:
    #             image: fedora_openmpi
    #         - debug_32bit_index:
    #             image: fedora_openmpi
    #         - debug_no_IO:
    #             image: fedora_openmpi

    # ubuntu_openmpi_gcc:
    #     jobs:
    #         - debug_and_coverage:
    #             image: ubuntu_openmpi
    #         - debug:
    #             image: ubuntu_openmpi
    #         - debug_32bit_index:
    #             image: ubuntu_openmpi
    #         - debug_no_IO:
    #             image: ubuntu_openmpi
    #         - release:
    #             image: ubuntu_openmpi

    # ubuntu_openmpi_clang:
    #     jobs:
    #         - debug:
    #             image: ubuntu_openmpi
    #             CC: clang
    #             CXX: clang++
    #         - release:
    #             image: ubuntu_openmpi
    #             CC: clang
    #             CXX: clang++
