version: 2

jobs:
    build:
        docker:
            - image: debian:buster

        steps:
            - run:
                name: Install dependencies
                command: >
                    apt-get update && apt-get -y install
                    mpich
                    cmake
                    git
                    libhdf5-dev

            - checkout

            - run:
                name: Initalize submodules
                command: git submodule update --init

            - run:
                name: Debug build (full)
                command: >
                    ./cmake_init.sh debug ./ &&
                    cd debug &&
                    make -j && make test

            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./ &&
                    cd release &&
                    make -j && make test

            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./ -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test
