version: 2

workflows:
    version: 2
    master:
        jobs:
            - "Setup"
            - "Test_1":
                requires: "Setup"
            - "Test_2":
                requires: "Setup"
            - "Test_3":
                requires: "Setup"
            - "Test_4":
                requires: "Setup"

jobs:
    "Setup":
        docker:
            - image: debian:buster

        steps:
            - run:
                name: Install dependencies
                command: >
                    apt-get update && apt-get -y install
                    mpich
                    cmake
                    git
                    curl
                    libhdf5-mpich-dev

            - checkout

            - run:
                name: Initalize submodules
                command: git submodule update --init

    "Test_1":
        steps:
            - run:
                name: Debug build (full, code coverage)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_COVERAGE=ON &&
                    cd debug &&
                    make -j && make gcov && make install

    "Test_2":
        steps:
            - run:
                name: Release build (full)
                command: >
                    ./cmake_init.sh release ./install &&
                    cd release &&
                    make -j && make test && make install

    "Test_3":
        steps:
            - run:
                name: Debug build (full; 32bit index)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_32BIT_INDEX=ON &&
                    cd debug &&
                    make -j && make test && make install

    "Test_4":
        steps:
            - run:
                name: Debug build (no libCubismIO.a)
                command: >
                    ./cmake_init.sh debug ./install -DCUBISM_IO=OFF &&
                    cd debug &&
                    make -j && make test && make install
