#!/usr/bin/env bash
# File       : clang_tidy
# Created    : Mon Jan 20 2020 11:31:29 AM (+0100)
# Author     : Fabian Wermelinger
# Description: Perform checks in sources (clang-tidy)
# Copyright 2020 ETH Zurich. All Rights Reserved.

TESTDIR='clang_tidy.data'
rm -rf ${TESTDIR}
mkdir -p ${TESTDIR}
cd ${TESTDIR}
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../../..
/usr/share/clang/run-clang-tidy.py
