#!/usr/bin/env bash
# File       : correct_style
# Created    : Mon Jan 20 2020 11:29:59 AM (+0100)
# Author     : Fabian Wermelinger
# Description: Utility to adjust source code according to style conventions
# Copyright 2020 ETH Zurich. All Rights Reserved.

HEADER='\.\./\.\./include/Cubism/.*\.h'
SOURCE='\.\./\.\./src/.*\.(c|cpp)'
TEST_H='\.\./\.\./test/[A-Z].*\.h'
TEST_S='\.\./\.\./test/[A-Z].*\.(c|cpp)'

# format in-place
find ../.. \
    -regextype 'egrep' \
    -regex "${HEADER}" -or \
    -regex "${SOURCE}" -or \
    -regex "${TEST_H}" -or \
    -regex "${TEST_S}" | \
    xargs -n6 -P2 clang-format -style=file -i "$@"
