#!/usr/bin/env bash
# File       : correct_style
# Created    : Sun Mar 31 2019 10:20:59 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Utility to adjust source code according to style conventions
# Copyright 2019 ETH Zurich. All Rights Reserved.

# check sanity
find ../.. -name "*.c" -or -name "*.cpp" | \
    xargs -n1 -P2 ./tidy

# format in-place
find ../.. -name "*.c" -or -name "*.cpp" -or -name "*.h" | \
    xargs -n6 -P2 ./format -i
