#!/usr/bin/env bash
# File       : format
# Created    : Sun Mar 31 2019 03:32:35 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Source code formatter based on LLVM:
#              Style:  https://llvm.org/docs/CodingStandards.html
#              Format: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
# Copyright 2019 ETH Zurich. All Rights Reserved.

read -r -d '' STYLE <<'EOF'
{
  BasedOnStyle: llvm,                      # LLVM defaults
  IndentWidth: 4,                          # indentation columns
  AccessModifierOffset: -4,                # no indent for public, private, etc.
  AlignEscapedNewlines: true,              # align '\' in multi-line macros
  AlignOperands: true,
  AlignTrailingComments: true,
  AllowShortIfStatementsOnASingleLine: false,
  IndentCaseLabels: false,
  KeepEmptyLinesAtTheStartOfBlocks: false,
  BinPackArguments:  false,
  BinPackParameters: false,
  BreakBeforeBraces: Linux,                # brace breaking style
}
EOF

clang-format -style="${STYLE}" "$@"
