#!/usr/bin/env bash
# File       : format
# Created    : Sun Mar 31 2019 03:32:35 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Source code formatter based on LLVM:
#              Style:  https://llvm.org/docs/CodingStandards.html
#              Format: https://clang.llvm.org/docs/ClangFormatStyleOptions.html
# Copyright 2019 ETH Zurich. All Rights Reserved.

clang-format -style=file "$@"
