#!/usr/bin/env bash
# File       : tidy
# Created    : Sun Mar 31 2019 03:33:31 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Tidy-up (refactor) source code according LLVM policy.  Enforce
#              braces around all statements and parentheses around parameter in
#              macro bodies.
# Copyright 2019 ETH Zurich. All Rights Reserved.

clang-tidy \
    -fix \
    -fix-errors \
    -header-filter=.* \
    --checks=readability-braces-around-statements,misc-macro-parentheses \
    ${1} \
    -- -I.
