#!/usr/bin/env bash
# File       : coverage
# Created    : Sun Feb 02 2020 10:56:45 PM (+0100)
# Author     : Fabian Wermelinger
# Description: Compute gcov coverage data
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

mkdir -p coverage
cd coverage
find ../ -type f -path ../coverage -prune -o -name "*.gcno" -exec gcov -b -p {} \;
