#!/usr/bin/env bash
# File       : covreport
# Created    : Sat Feb 08 2020 05:21:11 PM (+0100)
# Author     : Fabian Wermelinger
# Description: gcovr wrapper for coverage report
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
gcovr -g -k -s -e '.*googletest.*' -e '.*gtest.*' -r ${DIR}/../.. "$@"
