#!/usr/bin/env bash
# File       : covreport
# Created    : Sat May 16 2020 09:13:00 PM (+0200)
# Author     : Fabian Wermelinger
# Description: Generate html code coverage reports
# Copyright 2020 ETH Zurich. All Rights Reserved.
set -e

mkdir -p covhtml
gcovr -g -k -s -r .. \
    --filter ../include/ \
    --filter ../src/ \
    --filter ../test/ \
    --exclude ../test/googletest \
    --exclude ../test/gtest-mpi-listener \
    --exclude ../test/sandbox \
    --html --html-details -o covhtml/index.html \
    "$@"
